version: '3.8'
services:
  documentor:
    image: documentor:1.0.0
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "11434:11434"
      - "8000:8000"
    volumes:
      - ./data:/docu-mentor-service/documentor/data/
      - ./ollama:/root/.ollama
